// Builds the Pocket Service Manager folder for each service pack bundle.
//
//   node pmic/packs/ops/package-psm.js                -> ~/Downloads/<service_id>/ for every bundle
//   node pmic/packs/ops/package-psm.js <service_id>   -> just that one
//   node pmic/packs/ops/package-psm.js <id|all> <parent_dir>
//
// Layout: card.json + service.json (so PSM lists it), backend/ (this pack's server with its
// bundle.json), deploy/docker-compose.yaml. The pack reads the hub at http://pmic-hub-backend:8080
// with the hub's API token from pmic/.secrets/hub.env (made by node pmic/ops/package-psm.js).
// Unlike pmic-hub, these ARE paid services: PSM Register and Stake are the owner's call.
"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SECRET = path.join(ROOT, "..", ".secrets", "hub.env");
const only = process.argv[2] && process.argv[2] !== "all" ? process.argv[2] : null;
const PARENT = path.resolve(process.argv[3] || path.join(os.homedir(), "Downloads"));

if (!fs.existsSync(SECRET)) {
  console.error("pmic/.secrets/hub.env is missing: run node pmic/ops/package-psm.js first (it makes the hub tokens).");
  process.exit(2);
}
const apiToken = (fs.readFileSync(SECRET, "utf8").match(/^PMIC_API_TOKEN=([0-9a-f]+)$/m) || [])[1];
if (!apiToken) {
  console.error("PMIC_API_TOKEN not found in pmic/.secrets/hub.env");
  process.exit(2);
}

const bundles = fs.readdirSync(path.join(ROOT, "bundles")).filter((f) => f.endsWith(".json")).map((f) => JSON.parse(fs.readFileSync(path.join(ROOT, "bundles", f), "utf8")));
const chosen = bundles.filter((b) => !only || b.service_id === only);
if (!chosen.length) {
  console.error(`unknown service id '${only}'; one of: ${bundles.map((b) => b.service_id).join(", ")}`);
  process.exit(2);
}

const compose = (id) => `# ${id}: PMIC service pack in Pocket Service Manager's layout. Generated by
# pmic/packs/ops/package-psm.js; don't edit the copy.
#
# PSM: Deploy service "${id}" on hetzner-mainnet (health /healthz). The relayer then calls
# http://${id}-backend:8080. Register and Stake are separate, gated steps.

services:
  backend:
    build: ../backend
    image: ${id}-backend:latest
    container_name: ${id}-backend
    restart: unless-stopped
    environment:
      PORT: "8080"
      PACK_FILE: bundle.json
      PMIC_HUB_URL: http://pmic-hub-backend:8080
      PMIC_API_TOKEN: "${apiToken}"
    expose:
      - "8080"
    networks: [supplier]

networks:
  supplier:
    external: true
    name: pocket-supplier
`;

const out = [];
for (const b of chosen) {
  const dir = path.join(PARENT, b.service_id);
  fs.rmSync(path.join(dir, "backend"), { recursive: true, force: true });
  fs.mkdirSync(path.join(dir, "backend"), { recursive: true });
  fs.mkdirSync(path.join(dir, "deploy"), { recursive: true });
  for (const f of ["server.js", "package.json", "Dockerfile"]) fs.copyFileSync(path.join(ROOT, f), path.join(dir, "backend", f));
  fs.cpSync(path.join(ROOT, "lib"), path.join(dir, "backend", "lib"), { recursive: true });
  fs.writeFileSync(path.join(dir, "backend", "bundle.json"), JSON.stringify(b, null, 2) + "\n");
  fs.writeFileSync(path.join(dir, "deploy", "docker-compose.yaml"), compose(b.service_id));
  fs.copyFileSync(path.join(ROOT, "ops", b.service_id, "card.json"), path.join(dir, "card.json"));
  fs.writeFileSync(path.join(dir, "service.json"), JSON.stringify({ service_id: b.service_id, name: b.display_name, compute_units_per_relay: 100000, card: "card.json", networks: {} }, null, 2) + "\n");
  out.push({ service_id: b.service_id, folder: dir, backend_url: `http://${b.service_id}-backend:8080` });
}
console.log(JSON.stringify({ hub_token: "read from pmic/.secrets/hub.env (not printed)", packs: out }, null, 2));
